"""empty message

Revision ID: 08b94806443f
Revises: fc6526f411e0
Create Date: 2017-07-10 12:57:39.694229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b94806443f'
down_revision = 'fc6526f411e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('cb', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist', 'cb')
    # ### end Alembic commands ###
