"""empty message

Revision ID: fc6526f411e0
Revises: 
Create Date: 2017-07-10 12:57:15.399553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6526f411e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist', 'cb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('cb', sa.VARCHAR(length=35), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
